# ====================================================
# SocialConnect API - Configuração de Desenvolvimento
# ====================================================

# Nome da aplicação
spring.application.name=socialconnect-api

# Porta do servidor
server.port=8080

# ===========================================================
# Banco de Dados (PostgreSQL)
# ===========================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/socialconnect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123456

# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# Exibe as queries SQL no console (útil para aprendizado)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# Console H2 (Desabilitado com o uso do PostgreSQL)
# =========================================================
spring.h2.console.enabled=false

# ==========================================
# SpringDoc OpenAPI / Swagger UI
# ==========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.info.title=SocialConnect API
springdoc.info.description=API RESTful de gestão para instituições sociais (ITE005)
springdoc.info.version=0.0.1-SNAPSHOT

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true