CREATE TABLE beneficiarios
(
    id_beneficiario          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                     VARCHAR(150) NOT NULL,
    cpf                      VARCHAR(14)  NOT NULL,
    telefone                 VARCHAR(20) NULL,
    endereco                 VARCHAR(255) NULL,
    situacao_vulnerabilidade VARCHAR(500) NULL,
    data_cadastro            date         NOT NULL
);

CREATE INDEX idx_beneficiarios_cpf ON beneficiarios(cpf);

