CREATE TABLE doadores (
                          id_doador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome VARCHAR(150) NOT NULL,
                          tipo VARCHAR(20) NOT NULL
);